---
title: "Assignment Documents"
output: 
  html_document:
   toc: true
   toc_float: true
   theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F, message = F)
```
******

Assignments for this course will be programming exercises, and most of the content will be related to data analysis. Please refer to the Assignment Schedule for the release and submission dates. Assignments are to be completed using the Python programming language. All assignments will be posted to this section approximately 2 weeks before they are due, and will be submitted through Quercus (more detail on this will be included in the assignment files).

- Assignment documents containing the questions and other instructions will be distributed for each assignment. There will also be notebooks for [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb), an interactive programming environment that automatically includes most standard Python packages.

- Note: Even though some assignments may appear short, they take longer than expected to complete. Please do not leave things until the last minute. The first assignment will be posted after the second lecture. You can find the dates under the 'Schedule' section of the course website.

<!-- Two of the assignments (assignments 2 and 4) have __presentation components__. One of these presentations will be prerecorded and the other will be live. Both will have separate deadlines from the assignments themselves. More information will be provided later in the course. Presentation submission dates are also listed in the assignments schedule. -->

<br>

## Assignment 1 (COVID-19 Data Visualization)

<a href="https://docs.google.com/document/d/16NySq9dhDo5U8p5zqa5O3XOPAJWH3BGjiViBdfKi2p0/edit?usp=sharing">Instructions</a>

Due Jan 31st at 10:59am

## Reflection 1 

<a href="https://docs.google.com/document/d/12zSEZM9lBv7TREkq32dFHePDCSAouGGfcio27ithNCI/edit?usp=sharing">Instructions</a>

Due Feb 2nd at 10:59am

## Homework 2 (Exploring Income)

<a href="https://docs.google.com/document/d/1Wrt17KHvpQUTLjbDHUBMBroHm0H95j7mnbXjrU-6j1Q/edit?usp=sharing">Instructions</a>

Due Feb 14th at 10:59am

## Reflection 2 

<a href="https://docs.google.com/document/d/11Jr86y41iTUo54YLlJAS8Tfj4YGYWcFKaXYCCEfFROI/edit?usp=sharing">Instructions</a>

Due Feb 16th at 10:59am




<!-- <br> -->

<!-- ## Assignment 2: Exploring Income - Due Feb 8th -->

<!-- Here is the instruction file for Assignment 2: <a href="./docs/assign2-instructions.pdf" target="_blank">PDF Instructions</a> -->

<!-- <br> -->

<!-- ## Assignment 3: Simulation - Due Mar 8th -->

<!-- Here is the instruction file for Assignment 3: <a href="./docs/assign3-instructions.pdf" target="_blank">PDF Instructions</a> -->

<!-- <br> -->

<!-- ## Assignment 4: NLP - Due April 9th -->

<!-- Here is the instruction file for Assignment 4: <a href="https://drive.google.com/file/d/1hVhjHI67pE_ugP-A_S_Ijd6JPVEyhBLJ/view?usp=sharing" target="_blank">PDF Instructions</a> -->

<!-- Here are the Q1 datasets:  -->
<!-- <a href="https://drive.google.com/file/d/1im09d8Opyat9wAmLu35sxIEhAlpiGQSY/view?usp=sharing" target="_blank">training</a> |  -->
<!-- <a href="https://drive.google.com/file/d/10WF_uYMRvsDP_P7WZWC7ZQ2HTMu7LcR4/view?usp=sharing" target="_blank">testing</a> -->


<!-- <br> -->
