---
title: "JSC270H1S: Data Science I"
subtitle: "Syllabus - Draft (subject to change before the start of the course)"
date: Winter 2019
output: 
  html_document:
   toc: true
   toc_float: true
   theme: flatly
---


## Teaching Team 
- <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Prof. [N. Taback](http://utstat.toronto.edu/nathan/), SS6027C.
- <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Prof. [F. Chevalier](http://fannychevalier.net), BA5226.
- Email instructors: jsc270-winter2019@cs.toronto.edu
- Teaching assistants: Nicole Sultanum and Michael Moon.



## <i class="fa fa-clock-o" aria-hidden="true"></i> Course Office Hours 
- Prof. Taback, <mark>xxx</mark>.
- Prof. Chevalier, <mark>xxx</mark>.  
- The schedule of the TA office hours will be posted as soon as it is available.


## <i class="fa fa-calendar-times-o" aria-hidden="true"></i> Course Schedule 


### _Lectures_
- Wednesdays, 12:00-14:00 in [WI523](http://map.utoronto.ca/utsg/building/032A).
- There is no lecture on February 20 (Reading Week)

### _Tutorials_
- Mondays, 12:00-14:00 in [WI523](http://map.utoronto.ca/utsg/building/032A).  

- There are no tutorials on the following Mondays:  
      + January 7. <mark>You should complete the online orientation 1) to R and R Studio, 2) to python and Jupyter notebook, and 3) to github in lieu of this tutorial. </mark>
      + February 18 (Reading Week)  
      + March 11 (Mid-Term Test)

#### _Preparation_
- **In between Wednesdays and Mondays:** <mark>On Wednesdays, you will be provided with work to do in preparation for the next Monday's tutorial.  This may include computational work, readings, and/or practice problems.  Often you will be required to submit part of this work before tutorial and to bring part of this completed work to the tutorial.</mark>

## <span class="glyphicon glyphicon-education" aria-hidden="true"></span> Course Description and Learning Objectives 

Data Science is a relatively new interdisciplinary field that ecompasses statistic methods, the computational aspects of carrying out a data analysis, including acquisition, management, and analysis of data, and the communication of analysis processes and extracted knowledge. Statistical reasoning, computing with data, and visualization play important roles in this emerging discipline.  The purpose of this course is to give you a broad introduction to many of the ways analysts learn from data, including statistical reasoning, computation and communication. We will use both python and R programming languages and environments, and tutorials will introduce students to communicating statistical knowledge.

Through this course, you will gain experience working on data science projects that involve using data from industry, science, or the humanities to help answer salient questions; interact with data scientists, researchers, or other professionals from academia or industry; learn how to translate data science skills across domains and think critically about data and models of data; develop strong oral and written communication skills and the ability to work in multidisciplinary team.

#### Learning objectives 

By the end of this course, you should be able to:

- Seek and acquire data from various sources
- Assess the provenance, relevance and quality of third party data sets
- Understand what you can and you cannot do with third party data sets
- <mark> Add more...</mark>
- Work collaboratively in a multidisciplinary team
- Appropriately communicate the analytical processes and extracted knowledge to different audiences

## <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Topics 

- Scraping and cleaning of data
- Data wrangling and summarizing data
- Statistical testing and estimation
- Statistical models for description <mark>and prediction </mark>
- Data visualization
- Communicating processes and results
- Ethical issues in data collection and analysis

## Course Website

Class slides, notes, and other important information can be found on the [course website.](https://jsc270.github.io/)

## <span class="glyphicon glyphicon-book" aria-hidden="true"></span>  Optional Course Textbooks



[Baumer, B.S., Kaplan, D.T., and Horton, N.J. Modern Data Science with R. 2017. CRC Press](https://www.crcpress.com/Modern-Data-Science-with-R/Baumer-Kaplan-Horton/p/book/9781498724487).

[Diez, D. M., Barr, C.D., and Cetinkaya-Rundel, M. Introdcutory Statistics with Randomization and Simulation First Edition](https://www.openintro.org/stat/textbook.php?stat_book=isrs).  This is a free book.

[Hands-On Programming with R, by Garrett Grolemund](https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf). This is a free book.

[R for Data Science, by Hadley Wickham and Garrett Grolemund](http://r4ds.had.co.nz) is a wonderful resource. This is a free book.

## <i class="fa fa-code" aria-hidden="true"></i> Computing

See the different resource sections of the course website:
- [R Resources section](R_resources.html)
- <mark> [Python Resources section](Python_resources.html) </mark>
- <mark> See the [github Resources section](github_resources.html) </mark>

## <i class="fa fa-forumbee" aria-hidden="true"></i> Discussion Forum

We will be using Piazza as a platform for discussions. You can find our class page at: <https://piazza.com/utoronto.ca/fall2018/sta130h1/home>. Students will be able to post anonymously to classmates, but not instructors. 

Be sure to read Piazza’s [Privacy Policy](https://piazza.com/legal/privacy) and [Terms of Service](https://piazza.com/legal/terms) carefully. Take time to understand and be comfortable with what they say. They provide for substantial sharing and disclosure of your personal information held by Piazza, which affects your privacy.  If you decide to participate in Piazza, only provide content that you are comfortable sharing under the terms of the Privacy Policy and Terms of Use.

## <span class="glyphicon glyphicon-signal" aria-hidden="true"></span> Evaluation

<!--```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
eval <- read_csv(file = "JSC270-winter2019evaluation.csv",)
knitr::kable(eval)
```
-->

### Important notes about tutorials

- <mark>Your tutorial grade includes any assigned work that is due before tutorial and any work done during tutorial.  Note that if you miss a tutorial, there is no way to make up this component of your mark.</mark>



## <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> Missed Tests or Assignments

- If a test or tutorial work is missed for a valid medical reason, you must submit the University of Toronto Verification of [Student Illness or Injury form](http://www.illnessverification.utoronto.ca) within one week of the test.  Submit the form to your TA if it is related to missed tutorial work.  Submit the form to your instructor if it is related to the test.
- The form will only be accepted as valid if the form is filled out according to the instructions on the form.
- The form must indicate that the degree of incapacitation on academic functioning is moderate, serious, or severe in order to be considered a valid medical reason for missing the term test. If the form indicates that the degree of incapacitation on academic functioning is negligible or mild then this will NOT be considered a valid medical reason.
- If a tutorial is missed for a valid reason then the weight for that tutorial work will be shifted to the remaining tutorials.
- If the term test is missed for a valid reason then the weight for the test will be shifted to the final exam.  In other words, the final exam will be worth 57% of your final grade.  
- Other reasons for missing an assignment, tutorial work, or the term test will require prior approval by your instructor. If prior approval is not received for non-medical reasons then you will receive a grade of zero for the missed assignment, tutorial work, or test.

## <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> Marking Concerns

Any requests to have your test remarked must contain a written justification for consideration.  Remarking requests should be made within one week of receiving your test results.  Re-evaluation appeals are at the discretion of the instructors.  Note that adjustments in marks will be rare and could equally result in a lowering or raising of the mark.  If a re-revaluation is completed by the instructors, the student must accept the resulting mark as the new mark, whether it goes up or down or remains the same.  When appealing a re-evaluation decision, the student accepts this condition.

## <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> How to Communicate with Your Instructors

Always use your utoronto.ca e-mail account to ensure that your message doesn’t automatically go to a Junk folder and include your full name and student number. Violation to this policy may incur severe response delays. Allow up to 72 hours for a reply.

Questions about course material or organization, such as,
  
- What do I change the colour of my plotting symbol?
- How do I do question 3.7 in the textbook? 
- What is the difference between supervised and unsupervised learning?
- When is the term test?

<mark>should be posted on the discussion forums on Piazza or asked in person</mark>. Questions can be posted anonymously (so that the author is anonymous to other students but not to the instructors), if desired.

If your communication is private, such as, I missed the test because I was ill, then e-mail both instructors (jsc270-winter2019@cs.toronto.edu).  If you missed a tutorial then e-mail both TAs.






## <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> Academic Integrity

You are responsible for knowing the content of the [University of Toronto’s Code of Behaviour on Academic Matters](http://www.governingcouncil.utoronto.ca/policies/behaveac.htm).

As a general rule, we encourage you to discuss course material with each other and ask others for advice.  However, it is not permitted to share complete solutions or to directly share code for anything that is to be handed in.  When an assignment is required to be completed as a team, you may share solutions and code with other members of your team, but not with another team in the class.  For example, "For question 2.1 what R function did you use?" is a fair question; "Please show me your R code for question 2.1" is not.

If you have any questions about what is or is not permitted in this course, please do not hesitate to contact your instructors ([Prof. Chevalier](mailto:fanny.chevalier@utoronto.ca) if your last (family) name starts with A-L and [Prof. Taback](mailto:nathan.taback@utoronto.ca) if your last (family) name starts with M-Z).

## <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> Accessibility Needs

The University of Toronto is committed to accessibility. If you require accommodations for a disability, or have any accessibility concerns about the course, the class room, or course materials, please contact Accessibility Services as soon as possible: <accessibility.services@utoronto.ca> or <http://accessibility.utoronto.ca>

## <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Your Responsibilities

The course is designed to actively engage you in the course material. We hope you’ll find the methods of data science interesting, challenging, and fun. <mark>In order for classroom sessions and tutorials to be effective, prepare by learning about the week’s concepts through completing the recommended problems and readings. </mark>
