---
title: "Schedule"
output: 
  html_document:
   toc: true
   toc_float: true
   theme: yeti
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(warning = F, message = F)
```
<br>

# <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Evaluation Calendar
Written assignments are to be submitted via Quercus (please see the assignments section). The deadline for submission of assignments is 10:59am EST on Mondays (1 hour before class starts).

```{r, echo=FALSE}
library(tidyverse)
#jsc270courseassschedule <- read_csv("JSC270-winter2021-assignments-schedule.csv")
#knitr::kable(jsc270courseassschedule[1:6,])
```

<br>

# <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Course Schedule

Here is our tentative schedule, which may change as the course progresses.

```{r, echo=FALSE}
library(tidyverse)
library(kableExtra)
options(knitr.kable.NA = '')
my_backgrounds <- colorRampPalette(c("white", "gray"))(5)
jsc270courseschedule <- read_csv("Winter2022_schedule.csv")
knitr::kable(jsc270courseschedule[1:37,]) %>%  
  kable_styling(full_width = F)   %>%   
  row_spec(c(1:2, 6:8, 12:14, 17:19, 23:25, 29:31, 35:37),background = my_backgrounds[2]) 
```

******


